# @package _global_

defaults:
  - override /data: agilex_piper
  - override /model: fastwam
  - _self_

output_dir: /data/models/Motus_FastWAM/stage1/agilex_piper_${data.task_name}_4cam2x2_448_1e-5/${now:%Y-%m-%d}_${now:%H-%M-%S}
pretrain: true

# AgileX Piper real-world task training defaults.
batch_size: 8
num_workers: 4

lr_scheduler_type: "cosine"
learning_rate: 1.0e-5
num_epochs: 2
max_steps: null
log_every: 10
save_every: 2000
eval_every: 0

gradient_accumulation_steps: 1
weight_decay: 1.0e-2
resume: null

wandb:
  enabled: true
  workspace: sunxiaoquan_2002-huazhong-university-of-science-and-tech
  project: fast_wam-agilex-piper
  name: ${data.task_name}
  group: agilex_piper
  mode: online

model:
  mot_checkpoint_mixed_attn: false

data:
  task_name: press_button
  dataset_root: /data/datasets/fastwam/agilex_piper/press_button
  instruction: null
